### ISSUE TITLE
Depth plot

### ISSUE THREAD

**Issue by avnitkr** [nt246/physalia-lcwgs#3]
Greetings!

I am using the data processing pipeline for my whole genome data set. After calculating the depth of data, I am trying to plot the data using the R code provided. However, I keep getting the following error for depth.gz files for 29 individuals ( wgs data set):

Error in FUN(X[[i]], ...) :
  long vectors not supported yet: ../../../src/include/Rinlinedfuns.h:535
Calls: read_tsv ... col_lengths -> map_int -> map_mold -> vapply -> FUN
Execution halted

I am using the following R code-

module load R/4.0.0
R
library(tidyverse)

basedir <- "/g/data/ht96/Avneet_UQ/avneet_midcand/coverage/depth_samtools/LH/D01/" # Make sure to edit this to match your $BASEDIR
bam_list <- read_lines(paste0(basedir, "/bam_list.txt"))

for (i in 1:length(bam_list)){
  bamfile = bam_list[i]
  # Compute depth stats
  depth <- read_tsv(paste0(basedir, "/", bamfile, "_depth.gz"), col_names = F)$X1
  mean_depth <- mean(depth)
  sd_depth <- sd(depth)
  mean_depth_nonzero <- mean(depth[depth > 0])
  mean_depth_within2sd <- mean(depth[depth < mean_depth + 2 * sd_depth])
  median <- median(depth)
  presence <- as.logical(depth)
  proportion_of_reference_covered <- mean(presence)
  output_temp <- tibble(bamfile, mean_depth, sd_depth, mean_depth_nonzero, mean_depth_within2sd, median, proportion_of_reference_covered)

  # Bind stats into dataframe and store sample-specific per base depth and presence data
  if (i==1){
    output <- output_temp
    total_depth <- depth
    total_presence <- presence
  } else {
    output <- bind_rows(output, output_temp)
    total_depth <- total_depth + depth
    total_presence <- total_presence + presence
  }
}

output %>%
  mutate(across(where(is.numeric), round, 3))

# Plot the depth distribution (this may take a few minutes to run)
tibble(total_depth = total_depth, position = 1:length(total_depth))  %>%
  ggplot(aes(x = position, y = total_depth)) +
  geom_point(size = 0.1)

# Total depth per site across all individuals 
total_depth_summary <- count(tibble(total_depth = total_depth), total_depth)
total_presence_summary <- count(tibble(total_presence = total_presence), total_presence)
total_depth_summary %>%
  ggplot(aes(x = total_depth, y = n)) +
  geom_point()
total_depth_summary %>%
  ggplot(aes(x = total_depth, y = n)) +
  geom_point() +
  coord_cartesian(xlim=c(NA, 20))
total_presence_summary %>%
  ggplot(aes(x = total_presence, y = n)) +
  geom_col()

I would be grateful if you could help me with this?

Cheers,
Avneet

**Comment by nt246** [comment]
Hi Avneet,
I'm sorry we had overlooked the issue you raised for so long. It looks like the problem here is that you're trying to read in base-by-base depth estimates for a very long reference genome file, giving a larger input than the R functions used here (or your system memory) can handle. The approach we list here works well for taking a detailed look at a small section of a genome (e.g. we work with a 2 million bp section in the tutorial). If you want to summarize your mapping depth across an entire genome, probably one of the other approaches we mention in the tutorial will work better.
