### ISSUE TITLE
Calculating FST per site using `realSFS fst print` output

### ISSUE THREAD

**Issue by flopezo** [nt246/physalia-lcwgs#4]
Hello,

Thank you for creating these helpful ANGSD tutorials. In the "[Site Frequency Spectrum & Summary Statistics](https://github.com/nt246/physalia-lcwgs/blob/main/day_4/markdowns/sfs_summary_stats.md)" section, you write the following regarding how to calculate F<sub>ST</sub> per site:

> We can view the genetic variance components at each site with realSFS:
> 
> `$REALSFS fst print $RESDIR/PANY_vs_MAQU.fst.idx | less -S`
> 
> The columns are (1) chromosome, (2) position, (3) a<sub>s</sub> (between population genetic variance), and (4) b<sub>s</sub> (within population variance).
> 
> QUESTION
> 
> What is the value of F<sub>ST</sub> at position chr24:365?
> 
> a<sub>365</sub> = 0.017935 b<sub>365</sub> = 0.224872
> 
> F<sub>ST</sub> = a<sub>365</sub> / (a<sub>365</sub> + b<sub>365</sub>) = 0.017935 / (0.017935 + 0.224872) = 0.07386525
> 
> To calculate F<sub>ST</sub> for a region, you sum all as for the region and then divide that by the sum of all (a<sub>s</sub> + b<sub>s</sub>) in that region.

However, in the official ANGSD documentation ([here](https://www.popgen.dk/angsd/index.php/Fst#realSFS_fst_print) and [here](https://github.com/ANGSD/angsd/blob/master/doc/formats.pdf)), it says that `realSFS fst print` outputs alpha and beta coefficients (columns 3 and 4) and the [per-site estimate of F<sub>ST</sub> is the ratio](https://github.com/ANGSD/angsd/issues/421#issuecomment-1629878457) of both coefficients: alpha / beta. 

Therefore, in the tutorial's example, should F<sub>ST</sub> be a<sub>365</sub> / b<sub>365</sub> instead of a<sub>365</sub> / (a<sub>365</sub> + b<sub>365</sub>)?

**Comment by tplinderoth** [comment]
`realSFS fst print`  now gives the between-population genetic variance in column 3 and the total population variance (within-population + between-population variance) in column 4, so yes, F<sub>ST</sub> = (column 3 value)/(column 4 value). I have updated the tutorial. Thank you.
